projeto/core/urls.py
from django.urls import path

from projeto.core import views as v
from .views import TempAtividade, TempAtividadeCon, TempAtividadePen, CreateConclu, AtividadeDelete, CreatePende, CreateComprovante, ListComprovante, ListAguardando, CreateRetirada, UpdateRetirada, DeleteRetirada, CreateRelatorio, ListRelatorio

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('atividades/', TempAtividade.as_view(), name='ativv'),
    path('atividades/pendentes', TempAtividadePen.as_view(), name='ativvp'),
    path('atividades/concluidas', TempAtividadeCon.as_view(), name='ativvc'),
    path('create_attc/', CreateConclu.as_view(), name='create-concluida'),
    path('atividades/pendentes/<int:pk>/', AtividadeDelete.as_view(), name='delete-atividade'),
    path('create_attp/', CreatePende.as_view(), name='att-atividade-pendente'),
    path('comprovante-interno/', CreateComprovante.as_view(), name='create_comprovante'),
    path('list-comprovante/', ListComprovante.as_view(), name='list_comprovante'),
    path('list-retirada/', ListAguardando.as_view(), name='list_retirada'),
    path('create-retirada/', CreateRetirada.as_view(), name='create_retirada'),
    path('retirada-edit/<int:pk>/', UpdateRetirada.as_view(), name='update-retirada'),
    path('retirada-delete/<int:pk>/', DeleteRetirada.as_view(), name='delete-retirada'),
    path('balanco-mensal/', CreateRelatorio.as_view(), name='create-relatorio'),
    path('list-balanco/', ListRelatorio.as_view(), name='list-relatorio'),
]

projeto/estoque/urls.py
from django.urls import include, path

from projeto.estoque import views as v

app_name = 'estoque'


entrada_patterns = [
    path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

saida_patterns = [
    path('', v.EstoqueSaidaList.as_view(), name='estoque_saida_list'),
    path('add/', v.estoque_saida_add, name='estoque_saida_add'),
]

entrega_patterns = [
    path('', v.protocolo_de_entrega, name='protocolo_de_entrega_list'),
    path(
        '<int:pk>/',
        v.protocolo_de_entrega_detail,
        name='protocolo_de_entrega_detail'
    ),
    path(
        '<int:pk>/dar_baixa/',
        v.dar_baixa_no_estoque_com_protocolo_de_entrega,
        name='dar_baixa'
    ),
]

urlpatterns = [
    path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
    path('entrega/', include(entrega_patterns)),
]

projeto/produto/urls.py
from django.urls import path

from projeto.produto import views as v

app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('add2/', v.produto_add, name='produto_add2'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
    path('import/csv/', v.import_csv, name='import_csv'),
    path('export/csv/', v.export_csv, name='export_csv'),
    path('import/xlsx/', v.import_xlsx, name='import_xlsx'),
    path('export/xlsx/', v.exportar_produtos_xlsx, name='export_xlsx'),
    path(
        'import/csv/pandas/',
        v.import_csv_with_pandas,
        name='import_csv_with_pandas'
    ),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
]

projeto/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

class MetodoPag(models.Model):
    mpagamento = models.CharField(verbose_name='Metodo de Pagamento:', max_length=60, blank=True)
    descric = models.CharField(verbose_name='Descrição:', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.mpagamento)


class Conclu_Serviço(models.Model):
    serviço_concluido = models.CharField(verbose_name='Serviço Concluido?: ', max_length=60, blank=True)
    descric = models.CharField(verbose_name='Descrição:', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.serviço_concluido)



class AttPendete(models.Model):
    dono = models.CharField(verbose_name='Dono do aparelho:', max_length=60, blank=True)
    modelo_aparelho = models.CharField(verbose_name='Modelo do aparelho:', max_length=60, blank=True)
    concerto_aparelho = models.CharField(verbose_name='Problema do aparelho:', max_length=600, blank=True)
    valor_aparelho = models.CharField(verbose_name='Valor do Concerto:', max_length=60, blank=True)
    data_entrega_aparelho = models.CharField(verbose_name='Data para entregar:', max_length=60, blank=True)
    finalizado = models.ForeignKey(Conclu_Serviço, max_length=100, null=True, on_delete=models.PROTECT)



class AttConcluida(models.Model):
    dono_aparelho = models.CharField(verbose_name='Dono do aparelho:', max_length=60, blank=True)
    modelo = models.CharField(verbose_name='Modelo do aparelho:', max_length=60, blank=True)
    concerto = models.CharField(verbose_name='Problema do aparelho:', max_length=600, blank=True)
    valor = models.CharField(verbose_name='Valor do Concerto:', max_length=60, blank=True)
    data_da_manutencao = models.CharField(verbose_name='Data entregue:', max_length=60, blank=True)


class NotaFiscal(models.Model):
    n_cliente = models.CharField(verbose_name='Nome do Cliente:', max_length=60, blank=True)
    nf_fiscal = models.CharField(verbose_name='Codigo Fiscal:', max_length=60, blank=True)
    valor_pago = models.CharField(verbose_name='Valor Pago:', max_length=60, blank=True)
    data_venda = models.CharField(verbose_name='Data da Venda:', max_length=60, blank=True)
    hora_venda = models.CharField(verbose_name='Data da Venda:', max_length=60, blank=True)
    funcionario = models.CharField(verbose_name='Funcionário:', max_length=60, blank=True)
    metodo_pago = models.ForeignKey(MetodoPag, max_length=100, null=True, on_delete=models.PROTECT)


class AguardandoRetirada(models.Model):
    name_cliente = models.CharField(verbose_name='Nome ', max_length=60, null=False)
    m_aparelho = models.CharField(verbose_name='Modelo Do Aparelho ', max_length=60, null=False)
    Falta_Pagar = models.ForeignKey(Conclu_Serviço, max_length=100, null=False, on_delete=models.PROTECT)
    f_pagar_valor = models.CharField(verbose_name='Valor a Pagar: ', max_length=60, blank=True, null=True)


    def __str__(self):
        return "{}".format(self.m_aparelho)

############################################################################################################

class entrada_saida_att(models.Model):
    entrada_ou_saida = models.CharField(verbose_name='Compra ou Venda: ', max_length=60, blank=True)
    descric = models.CharField(verbose_name='Descrição:', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.entrada_ou_saida)


class mensal_diario(models.Model):
    mensal_diario = models.CharField(verbose_name='Diario ou Mensal: ', max_length=60, blank=True)
    descric = models.CharField(verbose_name='Descrição:', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.mensal_diario)


class positivo_negativo(models.Model):
    positiv_negativo = models.CharField(verbose_name='Positivo ou Negativo: ', max_length=60, blank=True)
    descric = models.CharField(verbose_name='Descrição:', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.positiv_negativo)


class relatorios(models.Model):
    compra_ou_venda = models.ForeignKey(entrada_saida_att, max_length=100, null=True, on_delete=models.PROTECT)
    valor_r = models.CharField(verbose_name='Valor: ', max_length=60, blank=True)
    motivo = models.CharField(verbose_name='Produto: ', max_length=60, blank=True)
    data_r = models.CharField(verbose_name='Data: ', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.valor_r)


class relatorio_mensal(models.Model):
    d_ou_m = models.ForeignKey(mensal_diario, max_length=100, null=False, on_delete=models.PROTECT)
    p_ou_n = models.ForeignKey(positivo_negativo, max_length=100, null=False, on_delete=models.PROTECT)
    total = models.CharField(verbose_name='Valor:', max_length=60, blank=True)
    mes_relatorio = models.CharField(verbose_name='Mês do Relatório: ', max_length=60, blank=True)
    data_rm = models.CharField(verbose_name='Dia do Relatório: ', max_length=60, blank=True)

    def __str__(self):
        return "{}".format(self.p_ou_n)

projeto/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import TemplateView
from .models import AttConcluida, AttPendete, NotaFiscal, AguardandoRetirada, relatorio_mensal, relatorios


def index(request):
    return render(request, 'index.html')


class TempAtividade(TemplateView):
    template_name = 'atividades.html'


class TempAtividadePen(ListView):
    model = AttPendete
    template_name = 'atividades-pendente.html'


class AtividadeDelete(UpdateView):
    model = AttPendete
    fields = ['data_entrega_aparelho', 'finalizado']
    template_name = 'attpendente-delete.html'
    success_url = ('/comprovante-interno')


class TempAtividadeCon(ListView):
    model = AttConcluida
    template_name = 'atividades-concluida.html'



class CreateConclu(CreateView):
    model = AttConcluida
    fields = ['dono_aparelho', 'modelo', 'concerto', 'valor', 'data_da_manutencao']
    template_name = 'attconcluidis.html'
    success_url = ('/')


class CreatePende(CreateView):
    model = AttPendete
    fields = ['dono', 'modelo_aparelho', 'concerto_aparelho', 'valor_aparelho', 'data_entrega_aparelho', 'finalizado']
    template_name = 'attconcluidis.html'
    success_url = ('/comprovante-interno')


class CreateComprovante(CreateView):
    model = relatorios
    fields = ['compra_ou_venda', 'valor_r', 'motivo', 'data_r']
    template_name = 'attconcluidis.html'
    success_url = ('/list-comprovante')


class ListComprovante(ListView):
    model = relatorios
    template_name = 'comprovante_int.html'


class ListAguardando(ListView):
    model = AguardandoRetirada
    template_name = 'aguardando-retirada.html'


class CreateRetirada(CreateView):
    model = AguardandoRetirada
    fields = ['name_cliente', 'm_aparelho', 'Falta_Pagar', 'f_pagar_valor']
    template_name = 'attconcluidis.html'
    success_url = ('/list-retirada')


class UpdateRetirada(UpdateView):
    model = AguardandoRetirada
    fields = ['name_cliente', 'm_aparelho', 'Falta_Pagar', 'f_pagar_valor']
    template_name = 'updateretirada.html'
    success_url = ('/list-retirada')


class DeleteRetirada(DeleteView):
    model = AguardandoRetirada
    template_name = 'delete-retirada.html'
    success_url = ('/list-retirada')


class CreateRelatorio(CreateView):
    model = relatorio_mensal
    fields = ['d_ou_m', 'p_ou_n', 'total', 'mes_relatorio', 'data_rm']
    template_name = 'attconcluidis.html'
    success_url = ('/list-balanco')


class ListRelatorio(ListView):
    model = relatorio_mensal
    template_name = 'list-relatorio.html'

projeto/core/templates/aguardando-retirada.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aguardando Retirada</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- Font-awesome -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
        <!-- Select2 -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="/">Eltec Celulares</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Produtos</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="{% url 'produto:produto_list' %}">Produtos</a> <!-- {% url 'produto:produto_list' %} -->
                            <!--<a class="dropdown-item" href="{% url 'produto:import_csv' %}">Importar CSV</a>
                            <a class="dropdown-item" href="{% url 'produto:export_csv' %}">Exportar CSV</a>
                            <a class="dropdown-item" href="{% url 'produto:import_xlsx' %}">Importar XLSX</a>
                            <a class="dropdown-item" href="{% url 'produto:export_xlsx' %}">Exportar XLSX</a>
                            <a class="dropdown-item" href="{% url 'produto:import_csv_with_pandas' %}">Importar CSV com Pandas</a> -->
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown02">
                            <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Reabastecer</a> <!-- {% url 'estoque:estoque_entrada_list' %} -->
                            <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Vender</a> <!-- {% url 'estoque:estoque_saida_list' %} -->
                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/create-retirada">Criar<span class="sr-only">(current)</span></a>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Protocolo de Entrega</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown03">
                            <a class="dropdown-item" href="{% url 'estoque:protocolo_de_entrega_list' %}">Entrega</a>
                        </div>
                    </li> -->
                </ul>
                {% if user.is_authenticated %}
                  <ul class="navbar-nav px-3">
                    <li class="nav-item text-nowrap">
                      <a href="{% url 'logout' %}" class="nav-link">Sair</a>
                    </li>
                  </ul>
                {% endif %}
            </div>
        </nav>
        
</head>
<body>
    <br><br><br><br>
    <style>
        body{
            background-color: rgb(60, 117, 202);
        }
        main{
            background-color: white;
            width: auto;
            height: auto;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 5px;
            border-radius: 15px;
            text-align: left;
            cursor: pointer;
            color: black;
            margin-left: 30px;
            margin-right: 30px;
            padding: 20px;
        }

    </style>
    <br><br>
        {% for AguardandoRetirada in object_list %}
        <main>
            <h3 style="font-weight: bold; text-align: left;">Dono: {{ AguardandoRetirada.name_cliente }}</h3> 
            <h3 style="font-weight: bold; text-align: left;">Falta Pagar?: {{ AguardandoRetirada.Falta_Pagar }}</h3>
            <hr>
            <h3 style="font-weight: bold; text-align: left;">Modelo: {{ AguardandoRetirada.m_aparelho }}</h3> 
            <h3 style="font-weight: bold; text-align: left;">Valor a Pagar: {{ AguardandoRetirada.f_pagar_valor }}</h3> 
            <hr>
            <a href="{% url 'core:update-retirada' AguardandoRetirada.id %}">
                <button type="button" class="btn btn-success" >Editar</button>
            </a>
            <a href="{% url 'core:delete-retirada' AguardandoRetirada.id %}">
                <button type="button" class="btn btn-danger" >Apagar</button>
            </a>
        </main>
        <br>
        {% empty %}
            <main>
                <h1 style="font-weight: bold;">Nenhum aparelho encontrado.</h1>
                <hr>
                <p style="font-weight: bold; font-size: 25px;">Todos os aparelhos em nosso sistema, foram entregues!</p>
            </main>
            <hr>
        {% endfor %}


<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</body>
</html>

projeto/core/templates/atividades-pendente.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Serviços Pendentes</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- Font-awesome -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
        <!-- Select2 -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="/">Eltec Celulares</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Produtos</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="{% url 'produto:produto_list' %}">Produtos</a> <!-- {% url 'produto:produto_list' %} -->
                            <!--<a class="dropdown-item" href="{% url 'produto:import_csv' %}">Importar CSV</a>
                            <a class="dropdown-item" href="{% url 'produto:export_csv' %}">Exportar CSV</a>
                            <a class="dropdown-item" href="{% url 'produto:import_xlsx' %}">Importar XLSX</a>
                            <a class="dropdown-item" href="{% url 'produto:export_xlsx' %}">Exportar XLSX</a>
                            <a class="dropdown-item" href="{% url 'produto:import_csv_with_pandas' %}">Importar CSV com Pandas</a> -->
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown02">
                            <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Reabastecer</a> <!-- {% url 'estoque:estoque_entrada_list' %} -->
                            <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Vender</a> <!-- {% url 'estoque:estoque_saida_list' %} -->
                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/create_attp">Criar Atividade <span class="sr-only">(current)</span></a>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Protocolo de Entrega</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown03">
                            <a class="dropdown-item" href="{% url 'estoque:protocolo_de_entrega_list' %}">Entrega</a>
                        </div>
                    </li> -->
                </ul>
                {% if user.is_authenticated %}
                  <ul class="navbar-nav px-3">
                    <li class="nav-item text-nowrap">
                      <a href="{% url 'logout' %}" class="nav-link">Sair</a>
                    </li>
                  </ul>
                {% endif %}
            </div>
        </nav>
        
</head>
<body>
    <br><br><br><br>
    <style>
        body{
            background-color: rgb(60, 117, 202);
        }
        main{
            background-color: white;
            width: auto;
            height: 500px;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 5px;
            border-radius: 15px;
            text-align: left;
            cursor: pointer;
            color: black;
            margin-left: 30px;
            margin-right: 30px;
            padding: 20px;
        }

    </style>
    <br><br>
        {% for AttPendete in object_list %}
        <main>
            <h3 style="font-weight: bold; text-align: left;">Dono: {{ AttPendete.dono }}</h3> <br>
            <h3 style="font-weight: bold; text-align: left;">Finalizado?: {{ AttPendete.finalizado }}</h3>
            <hr>
            <h3 style="font-weight: bold; text-align: left;">Modelo: {{ AttPendete.modelo_aparelho }}</h3> <br>
            <h3 style="font-weight: bold; text-align: left;">Serviço: {{ AttPendete.concerto_aparelho }}</h3> <br>
            <h3 style="font-weight: bold; text-align: left;">Valor: {{ AttPendete.valor_aparelho }}</h3> <br>
            <h3 style="font-weight: bold; text-align: left;">Entregar até: {{ AttPendete.data_entrega_aparelho }}</h3> <br>
            <a href="{% url 'core:delete-atividade' AttPendete.id %}">
                <button type="button" class="btn btn-success" >Editar</button>
            </a>
            <hr>
        </main>
        <br>
        {% empty %}
            <main>
                <h1 style="font-weight: bold;">Nenhum serviço pendente encontrado.</h1>
                <hr>
                <p style="font-weight: bold; font-size: 25px;">Todos os serviços em nosso sistema estão concluidos!</p>
            </main>
            <hr>
        {% endfor %}

<br><br><br>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</body>
</html>