projeto/produto/urls.py
from django.urls import path

from projeto.produto import views as v

app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('add2/', v.produto_add, name='produto_add2'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
    path('import/csv/', v.import_csv, name='import_csv'),
    path('export/csv/', v.export_csv, name='export_csv'),
    path('import/xlsx/', v.import_xlsx, name='import_xlsx'),
    path('export/xlsx/', v.exportar_produtos_xlsx, name='export_xlsx'),
    path(
        'import/csv/pandas/',
        v.import_csv_with_pandas,
        name='import_csv_with_pandas'
    ),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
]

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)
    data = models.DateField(null=True, blank=True)
    categoria = models.ForeignKey(
        'Categoria',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }


class Categoria(models.Model):
    categoria = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ('categoria',)

    def __str__(self):
        return self.categoria

projeto/produto/forms.py
from django import forms

from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

projeto/produto/views.py
import csv
import io
from datetime import datetime

from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView

from projeto.produto.actions.export_xlsx import export_xlsx
from projeto.produto.actions.import_xlsx import \
    import_xlsx as action_import_xlsx

from .forms import ProdutoForm
from .models import Produto


def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    search = request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list': objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super(ProdutoList, self).get_queryset()
        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(
                Q(produto__icontains=search) |
                Q(ncm__icontains=search)
            )
        return queryset


def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def produto_add(request):
    form = ProdutoForm(request.POST or None)
    template_name = 'produto_form2.html'

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('produto:produto_list'))

    context = {'form': form}
    return render(request, template_name, context)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    ''' Retorna o produto, id e estoque. '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        produto = item.get('produto')
        ncm = str(item.get('ncm'))
        importado = True if item.get('importado') == 'True' else False
        preco = item.get('preco')
        estoque = item.get('estoque')
        estoque_minimo = item.get('estoque_minimo')
        obj = Produto(
            produto=produto,
            ncm=ncm,
            importado=importado,
            preco=preco,
            estoque=estoque,
            estoque_minimo=estoque_minimo,
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)


def import_csv(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        # Lendo arquivo InMemoryUploadedFile
        file = myfile.read().decode('utf-8')
        reader = csv.DictReader(io.StringIO(file))
        # Gerando uma list comprehension
        data = [line for line in reader]
        save_data(data)
        return HttpResponseRedirect(reverse('produto:produto_list'))

    template_name = 'produto_import.html'
    return render(request, template_name)


def export_csv(request):
    header = (
        'importado', 'ncm', 'produto', 'preco', 'estoque', 'estoque_minimo',
    )
    produtos = Produto.objects.all().values_list(*header)
    with open('fix/produtos_exportados.csv', 'w') as csvfile:
        produto_writer = csv.writer(csvfile)
        produto_writer.writerow(header)
        for produto in produtos:
            produto_writer.writerow(produto)
    messages.success(request, 'Produtos exportados com sucesso.')
    return HttpResponseRedirect(reverse('produto:produto_list'))


def import_xlsx(request):
    filename = 'fix/produtos.xlsx'
    action_import_xlsx(filename)
    messages.success(request, 'Produtos importados com sucesso.')
    return HttpResponseRedirect(reverse('produto:produto_list'))


def exportar_produtos_xlsx(request):
    MDATA = datetime.now().strftime('%Y-%m-%d')
    model = 'Produto'
    filename = 'produtos_exportados.xlsx'
    _filename = filename.split('.')
    filename_final = f'{_filename[0]}_{MDATA}.{_filename[1]}'
    queryset = Produto.objects.all().values_list(
        'importado',
        'ncm',
        'produto',
        'preco',
        'estoque',
        'estoque_minimo',
        'categoria__categoria',
    )
    columns = ('Importado', 'NCM', 'Produto', 'Preço',
               'Estoque', 'Estoque mínimo', 'Categoria')
    response = export_xlsx(model, filename_final, queryset, columns)
    return response


def import_csv_with_pandas(request):
    filename = 'fix/produtos.csv'
    df = pd.read_csv(filename)
    aux = []
    for row in df.values:
        obj = Produto(
            produto=row[0],
            ncm=row[1],
            importado=row[2],
            preco=row[3],
            estoque=row[4],
            estoque_minimo=row[5],
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)
    messages.success(request, 'Produtos importados com sucesso.')
    return HttpResponseRedirect(reverse('produto:produto_list'))

projeto/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'produto:produto_list' %}">Voltar</a>

<h1>{{ object }}
  <span class="pull-right">
    <a href="{% url 'produto:produto_edit' object.pk %}">
      <button type="button" class="btn btn-success">
        <span class="fa fa-pencil"></span> Editar
      </button>
    </a>
  </span>
</h1>

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="text-right">Importado</th>
        <td>
          {% if object.importado %}
            <i class="fa fa-check-circle ok"></i>
          {% else %}
            <i class="fa fa-minus-circle no"></i>
          {% endif %}
        </td>
      </tr>
      <tr>
        <th class="text-right">NCM</th>
        <td>{{ object.ncm }}</td>
      </tr>
      <tr>
        <th class="text-right">Preço</th>
        <td>R$ {{ object.preco }}</td>
      </tr>
      <tr>
        <th class="text-right">Estoque</th>
        <td>{{ object.estoque }}</td>
      </tr>
      <tr>
        <th class="text-right">Estoque mínimo</th>
        <td>{{ object.estoque_minimo }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

projeto/produto/templates/produto_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<form method="POST" novalidate>
  {% csrf_token %}
  {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif%}">
      <label for="{{ field.id_for_label }}">
        {% if field.field.required %}
          <span class="required">{{ field.label }} </span>
        {% else %}
          {{ field.label }}
        {% endif %}
      </label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
      {% endfor %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}

<script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

projeto/produto/templates/produto_form2.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<form method="POST" novalidate>
  {% csrf_token %}

    <div class="form-group">
      <label for="id_importado">
        
          Importado
        
      </label>
      <input type="checkbox" name="importado" class="form-control" id="id_importado">
      
    </div>
  
    <div class="form-group">
      <label for="id_ncm">
        
          <span class="required">NCM </span>
        
      </label>
      <input type="text" name="ncm" maxlength="8" class="form-control" required id="id_ncm">
      
    </div>
  
    <div class="form-group">
      <label for="id_produto">
        
          <span class="required">Produto </span>
        
      </label>
      <input type="text" name="produto" maxlength="100" class="form-control" required id="id_produto">
      
    </div>
  
    <div class="form-group">
      <label for="id_preco">
        
          <span class="required">Preço </span>
        
      </label>
      <input type="number" name="preco" step="0.01" class="form-control" required id="id_preco">
      
    </div>
  
    <div class="form-group">
      <label for="id_estoque">
        
          <span class="required">Estoque atual </span>
        
      </label>
      <input type="number" name="estoque" class="form-control" required id="id_estoque">
      
    </div>
  
    <div class="form-group">
      <label for="id_estoque_minimo">
        
          <span class="required">Estoque mínimo </span>
        
      </label>
      <input type="number" name="estoque_minimo" value="0" min="0" class="form-control" required id="id_estoque_minimo">
      
    </div>
  
    <div class="form-group">
      <label for="id_data">
        
          Data
        
      </label>
      <input type="text" name="data" class="form-control" id="id_data">
      
    </div>
  
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}

<script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

projeto/produto/templates/produto_import.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input name="myfile" type="file" />
  <button type="submit" class="btn btn-success">Upload</button>
</form>

{% endblock content %}

projeto/produto/templates/produto_list.html
{% extends "base.html" %}

{% block content %}

{% for message in messages %}
  {% if 'success' in message.tags %}
    <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
  {% else %}
    <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
  {% endif %}
{% endfor %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lista de Produtos
    <span class="pull-right">
      <a href="{% url 'produto:produto_add' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
      <!--<a href="{% url 'produto:produto_add2' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar usando função
        </button>
      </a>-->
    </span>
  </h2>

  {% if object_list %}
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Importado</th>
          <th>NCM</th>
          <th>Produto</th>
          <th>Preço</th>
          <th class="text-center">Estoque</th>
          <th class="text-center">Estoque mínimo</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>
              {% if object.importado %}
                <i class="fa fa-check-circle ok"></i>
              {% else %}
                <i class="fa fa-minus-circle no"></i>
              {% endif %}
            </td>
            <td>{{ object.ncm }}</td>
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
            </td>
            <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
            <td class="text-center">{{ object.estoque }}</td>
            <td class="text-center">{{ object.estoque_minimo }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% include "includes/pagination.html" %}

{% endblock content %}

{% block js %}

<script>
  // Close alert after 2 seconds
  window.setTimeout(function() {
    $('.alert').fadeTo(500, 0).slideUp(500, function() {
      $(this).remove();
    });
  }, 2000);
</script>

{% endblock js %}