projeto/estoque/urls.py
from django.urls import include, path

from projeto.estoque import views as v

app_name = 'estoque'


entrada_patterns = [
    path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

saida_patterns = [
    path('', v.EstoqueSaidaList.as_view(), name='estoque_saida_list'),
    path('add/', v.estoque_saida_add, name='estoque_saida_add'),
]

entrega_patterns = [
    path('', v.protocolo_de_entrega, name='protocolo_de_entrega_list'),
    path(
        '<int:pk>/',
        v.protocolo_de_entrega_detail,
        name='protocolo_de_entrega_detail'
    ),
    path(
        '<int:pk>/dar_baixa/',
        v.dar_baixa_no_estoque_com_protocolo_de_entrega,
        name='dar_baixa'
    ),
]

urlpatterns = [
    path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
    path('entrega/', include(entrega_patterns)),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
]

projeto/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy

from projeto.core.models import TimeStampedModel
from projeto.produto.models import Produto

from .managers import EstoqueEntradaManager, EstoqueSaidaManager

MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)


class Estoque(TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        if self.nf:
            return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d-%m-%Y'))
        return '{} --- {}'.format(self.pk, self.created.strftime('%d-%m-%Y'))

    def nf_formated(self):
        if self.nf:
            return str(self.nf).zfill(3)
        return '---'


class EstoqueEntrada(Estoque):

    objects = EstoqueEntradaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque entrada'
        verbose_name_plural = 'estoque entrada'


class EstoqueSaida(Estoque):

    objects = EstoqueSaidaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque saída'
        verbose_name_plural = 'estoque saída'


class EstoqueItens(models.Model):
    estoque = models.ForeignKey(
        Estoque,
        on_delete=models.CASCADE,
        related_name='estoques'
    )
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField(blank=True)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)


class ProtocoloEntrega(TimeStampedModel):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    estoque_atualizado = models.BooleanField(default=False)

    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse_lazy('estoque:protocolo_de_entrega_detail', kwargs={'pk': self.pk})


class ProtocoloEntregaItens(models.Model):
    protocolo_entrega = models.ForeignKey(
        ProtocoloEntrega,
        on_delete=models.CASCADE,
        related_name='protocolo_entrega'
    )
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.protocolo_entrega.pk, self.produto)

projeto/estoque/forms.py
from django import forms

from projeto.produto.models import Produto

from .models import Estoque, EstoqueItens


class EstoqueForm(forms.ModelForm):

    class Meta:
        model = Estoque
        fields = ('nf',)


class EstoqueItensEntradaForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'


class EstoqueItensSaidaForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EstoqueItensSaidaForm, self).__init__(*args, **kwargs)
        # Retorna somente produtos com estoque maior do que zero.
        self.fields['produto'].queryset = Produto.objects.filter(estoque__gt=0)

projeto/estoque/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.urls import reverse
from django.views.generic import DetailView, ListView

from projeto.produto.models import Produto

from .forms import (
    EstoqueForm,
    EstoqueItensEntradaForm,
    EstoqueItensSaidaForm
)
from .models import (
    Estoque,
    EstoqueEntrada,
    EstoqueItens,
    EstoqueSaida,
    ProtocoloEntrega
)


def estoque_entrada_list(request):
    template_name = 'estoque_list.html'
    objects = EstoqueEntrada.objects.all()
    context = {
        'object_list': objects,
        'titulo': 'Entrada',
        'url_add': 'estoque:estoque_entrada_add'
    }
    return render(request, template_name, context)


class EstoqueEntradaList(ListView):
    model = EstoqueEntrada
    template_name = 'estoque_list.html'

    def get_context_data(self, **kwargs):
        context = super(EstoqueEntradaList, self).get_context_data(**kwargs)
        context['titulo'] = 'Entrada'
        context['url_add'] = 'estoque:estoque_entrada_add'
        return context


def estoque_entrada_detail(request, pk):
    template_name = 'estoque_detail.html'
    obj = EstoqueEntrada.objects.get(pk=pk)
    context = {
        'object': obj,
        'url_list': 'estoque:estoque_entrada_list'
    }
    return render(request, template_name, context)


class EstoqueDetail(DetailView):
    model = Estoque
    template_name = 'estoque_detail.html'


def dar_baixa_estoque(form):
    # Pega os produtos a partir da instância do formulário (Estoque).
    produtos = form.estoques.all()
    for item in produtos:
        produto = Produto.objects.get(pk=item.produto.pk)
        produto.estoque = item.saldo
        produto.save()
    print('Estoque atualizado com sucesso.')


def estoque_add(request, form_inline, template_name, movimento, url):
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(
        Estoque,
        EstoqueItens,
        form=form_inline,
        extra=0,
        can_delete=False,
        min_num=1,
        validate_min=True,
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_formset(
            request.POST,
            instance=estoque_form,
            prefix='estoque'
        )
        if form.is_valid() and formset.is_valid():
            form = form.save(commit=False)
            form.funcionario = request.user
            form.movimento = movimento
            form.save()
            formset.save()
            dar_baixa_estoque(form)
            return {'pk': form.pk}
    else:
        form = EstoqueForm(instance=estoque_form, prefix='main')
        formset = item_estoque_formset(instance=estoque_form, prefix='estoque')
    context = {'form': form, 'formset': formset}
    return context


@login_required
def estoque_entrada_add(request):
    form_inline = EstoqueItensEntradaForm
    template_name = 'estoque_entrada_form.html'
    movimento = 'e'
    url = 'estoque:estoque_detail'
    context = estoque_add(request, form_inline, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url, context.get('pk')))
    return render(request, template_name, context)


def estoque_saida_list(request):
    template_name = 'estoque_list.html'
    objects = EstoqueSaida.objects.all()
    context = {
        'object_list': objects,
        'titulo': 'Saída',
        'url_add': 'estoque:estoque_saida_add'
    }
    return render(request, template_name, context)


class EstoqueSaidaList(ListView):
    model = EstoqueSaida
    template_name = 'estoque_list.html'

    def get_context_data(self, **kwargs):
        context = super(EstoqueSaidaList, self).get_context_data(**kwargs)
        context['titulo'] = 'Saída'
        context['url_add'] = 'estoque:estoque_saida_add'
        return context


def estoque_saida_detail(request, pk):
    template_name = 'estoque_detail.html'
    obj = EstoqueSaida.objects.get(pk=pk)
    context = {
        'object': obj,
        'url_list': 'estoque:estoque_saida_list'
    }
    return render(request, template_name, context)


@login_required
def estoque_saida_add(request):
    form_inline = EstoqueItensSaidaForm
    template_name = 'estoque_saida_form.html'
    movimento = 's'
    url = 'estoque:estoque_detail'
    context = estoque_add(request, form_inline, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url, context.get('pk')))
    return render(request, template_name, context)


def protocolo_de_entrega(request):
    template_name = 'protocolo_de_entrega_list.html'
    objects = ProtocoloEntrega.objects.all()
    context = {
        'object_list': objects,
    }
    return render(request, template_name, context)


@login_required
def protocolo_de_entrega_detail(request, pk):
    template_name = 'protocolo_de_entrega_detail.html'
    obj = ProtocoloEntrega.objects.get(pk=pk)
    context = {
        'object': obj,
    }
    return render(request, template_name, context)


def dar_baixa_no_estoque_com_protocolo_de_entrega(request, pk):
    entrega = ProtocoloEntrega.objects.get(pk=pk)

    if entrega.estoque_atualizado:
        messages.error(request, 'Já foi dado baixa nessa entrega.')
        return HttpResponseRedirect(reverse('produto:produto_list'))

    # criar um Estoque saida
    estoque_saida = EstoqueSaida.objects.create(
        funcionario=request.user,
        movimento='s'
    )
    for item in entrega.protocolo_entrega.all():
        # Criar um Estoque Saida Detail
        EstoqueItens.objects.create(
            estoque=estoque_saida,
            produto=item.produto,
            quantidade=item.quantidade,
            saldo=item.produto.estoque - item.quantidade
        )
        # Dar baixa no estoque
        produtos = estoque_saida.estoques.all()
        for item_produto in produtos:
            produto = Produto.objects.get(pk=item_produto.produto.pk)
            produto.estoque = item_produto.saldo
            produto.save()
    entrega.estoque_atualizado = True
    entrega.save()
    messages.success(request, 'Estoque atualizado com sucesso.')
    return HttpResponseRedirect(reverse('produto:produto_list'))

projeto/estoque/templates/estoque_detail.html
{% extends "base.html" %}

{% block content %}

{% if object.movimento == 'e' %}
  <a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>
{% else %}
  <a href="{% url 'estoque:estoque_saida_list' %}">Voltar</a>
{% endif %}

{% if object.movimento == 'e' %}
  <h1>Reabastecimento: {{ object }}</h1>
{% else %}
  <h1>Venda: {{ object }}</h1>
{% endif %}

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="text-left">NF</th>
        <td>{{ object.nf_formated }}</td>
      </tr>
      <tr>
        <th class="text-left">Data</th>
        <td>{{ object.created }}</td>
      </tr>
      <tr>
        <th class="text-left">Funcionário</th>
        <td>{{ object.funcionario.first_name }}</td>
      </tr>
    </tbody>
  </table>
</div>
<br>
<a href="/list-comprovante"><button type="button" class="btn btn-primary">Adcionar Registro</button></a>
<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Saldo</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object.estoques.all %}
      <tr>
        <td>{{ obj.produto }}</td>
        <td>{{ obj.quantidade }}</td>
        <td>{{ obj.saldo }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

projeto/estoque/templates/estoque_entrada_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
  </style>

{% endblock css %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>

<div class="row">
  <div class="cols">
    <form method="POST" novalidate>
      {% csrf_token %}
      <legend style="border-bottom: 1px solid #e5e5e5;">Estoque Entrada</legend>

      <div class="row">
        <div class="col-sm-6">
          {% for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error {% endif%}">
              <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                  <span class="required">{{ field.label }} </span>
                {% else %}
                  {{ field.label }}
                {% endif %}
              </label>
              {% render_field field class="form-control" %}
              {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
              {% endfor %}
            </div>
          {% endfor %}
        {{ formset.management_form }}
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
          <div id="estoque" class="form-inline">
            {% for item_estoque_form in formset %}
              <div id="item-{{ forloop.counter0 }}" class="form-group">
                {{ item_estoque_form|bootstrap }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

      <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
        <i class="fa fa-plus"></i> Adicionar
      </span>

      <div class="row float-right">
        <div class="col-sm-12" style="margin-top: 10px;">
          <div class="form-inline buttons">
            <button class="btn btn-primary" value="Save">
              <i class="fa fa-floppy-o"></i>
              Salvar
            </button>
            <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">
              <i class="fa fa-times"></i>
              Cancelar
            </a>
          </div>
        </div>
      </div>

    </form>
  </div>
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/estoque_entrada.js' %}"></script>

<script type="text/html" id="item-estoque">
  <div id="item-__prefix__" class="form-group">
    {{ formset.empty_form|bootstrap }}
  </div>
</script>


{% endblock js %}

projeto/estoque/templates/estoque_list.html
{% extends "base.html" %}

{% block content %}

<h2>Estoque {{ titulo }}
  <span class="pull-right">
    <a href="{% url url_add %}">
      <button type="button" class="btn btn-primary">
        <span class="fa fa-plus"></span> Adicionar
      </button>
    </a>
  </span>
</h2>

{% if object_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Item</th>
        <th>NF</th>
        <th>Data</th>
        <th>Funcionário</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{% url 'estoque:estoque_detail' object.pk %}">{{ object }}</a>
          </td>
          <td>{{ object.nf_formated }}</td>
          <td>{{ object.created }}</td>
          <td>{{ object.funcionario.first_name }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

{% endblock content %}

projeto/estoque/templates/estoque_saida_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
  </style>

{% endblock css %}

{% block content %}

<a href="{% url 'estoque:estoque_saida_list' %}">Voltar</a>

<div class="row">
  <div class="cols">
    <form method="POST" novalidate>
      {% csrf_token %}
      <legend style="border-bottom: 1px solid #e5e5e5;">Estoque Saída</legend>

      <div class="row">
        <div class="col-sm-6">
          {% for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error {% endif%}">
              <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                  <span class="required">{{ field.label }} </span>
                {% else %}
                  {{ field.label }}
                {% endif %}
              </label>
              {% render_field field class="form-control" %}
              {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
              {% endfor %}
            </div>
          {% endfor %}
        {{ formset.management_form }}
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
          <div id="estoque" class="form-inline">
            {% for item_estoque_form in formset %}
              <div id="item-{{ forloop.counter0 }}" class="form-group">
                {{ item_estoque_form|bootstrap }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

      <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
        <i class="fa fa-plus"></i> Adicionar
      </span>

      <div class="row float-right">
        <div class="col-sm-12" style="margin-top: 10px;">
          <div class="form-inline buttons">
            <button class="btn btn-primary" value="Save">
              <i class="fa fa-floppy-o"></i>
              Salvar
            </button>
            <a href="{% url 'estoque:estoque_saida_list' %}" class="btn btn-danger">
              <i class="fa fa-times"></i>
              Cancelar
            </a>
          </div>
        </div>
      </div>

    </form>
  </div>
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/estoque_saida.js' %}"></script>

<script type="text/html" id="item-estoque">
  <div id="item-__prefix__" class="form-group">
    {{ formset.empty_form|bootstrap }}
  </div>
</script>


{% endblock js %}

projeto/estoque/templates/protocolo_de_entrega_detail.html
{% extends "base.html" %}

{% block content %}

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="text-right">NF</th>
        <td>{{ object }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% if not object.estoque_atualizado %}
  <span class="pull-right">
    <a href="{% url 'estoque:dar_baixa' object.pk %}">
      <button type="button" class="btn btn-primary">
        <span class="fa fa-plus"></span> Dar baixa no estoque
      </button>
    </a>
  </span>
{% endif %}

<table class="table table-striped">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object.protocolo_entrega.all %}
    <tr>
      <td>{{ obj.produto }}</td>
      <td>{{ obj.quantidade }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

projeto/estoque/templates/protocolo_de_entrega_list.html
{% extends "base.html" %}

{% block content %}

<h2>Protocolos de Entrega <small class="h6" style="color: red">Crie pelo Admin</small></h2>

{% if object_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Item</th>
        <th>Funcionário</th>
        <th>Estoque atualizado</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
          <td>{{ object.usuario.get_full_name }}</td>
          <td>
            {% if object.estoque_atualizado %}
                <i class="fa fa-check-circle ok"></i>
              {% else %}
                <i class="fa fa-minus-circle no"></i>
              {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

{% endblock content %}